### ISSUE TITLE
Seek bars on list layout cues

### ISSUE THREAD

**Issue by nodiscc** [FrancescoCeruti/linux-show-player#35]
Followup to #31 

>  It would be nice to be able to drag the timeline indicator in a running cue. i.e. move and jump forward or back on the time line while the cue is running.

>  > This is already possible from the pre-pre-pre-pre-never-published-alfa :laughing: I use this function myself a lot;you can drag the "blue" bar, the only inconvenient is that using the ListLayout you need to start the cue before.

**Comment by FrancescoCeruti** [comment]
mmh, maybe it's not clear to me, but, isn't this already possible? We are talking about something like the per button seek-bars of the cart-layout, right?

**Comment by nodiscc** [comment]
Yes.

**Comment by FrancescoCeruti** [comment]
mmh, ok, this can be already done form the right panel in the ListLayout.
If we are talking about adding a seekbar directly to the cue list or to add the ability to seek from the time indicator (the "Action" column), I dislike the idea, the first may take too much some space to be useful, and the second be quite risky (erroneous clicks), since it's not clearly distinguishable as seekbar.

**Comment by macdroid53** [comment]
I was not aware that the right panel time slider could be used in this manor.

And, that is what I was imagining, I was not suggesting adding to the cue list.

**Comment by FrancescoCeruti** [comment]
oook, just as I thought, maybe it's worth mentioning it in the docs :)
