### ISSUE TITLE
Countdown timer problem, backround color & font color selection

### ISSUE THREAD

**Issue by MarioGreenway** [FrancescoCeruti/linux-show-player#73]
I was just carrying on looking through the software to find bugs :) I hope I don't bother you...

Countdown timer (show playing cues ) doesn't adapt to Media Cue Properties ( start- , stop position),
but shows the time remaining to the end of cue, rather than to the "stop position" - setting

Set Font Size, Select background color, Select font color in cue Properties ( List Mode) doesn't seem to work - or at least I haven't figured it out yet. ( they do perfectly work in Cart Layout)
Being able to color the cues in List mode ( I don't know if one isn't meant to be able to do that yet) would be great!
The font size should also be possible, as it is already implemented in Cart - Layout. On the other hand, the height of the individual cues in the cue list would need to be variable, so maybe it would be easier to do a global font size in list layout.

The windows for selecting background and font color change to the selected color after choosing one. Example: I choose red background for cue 1, the background color of the window, to change the background color, is fully red as well. 
This doesn't make it easy to choose the right settings, and makes it really difficult to read the values, if for example the window is white.

**Comment by FrancescoCeruti** [comment]
>  was just carrying on looking through the software to find bugs :) I hope I don't bother you...

Not at all :)

> Countdown timer (show playing cues ) doesn't adapt to Media Cue Properties ( start- , stop position),
but shows the time remaining to the end of cue, rather than to the "stop position" - setting

Right now it's intentionally left like this, anyway it should be rather easy to achieve

> Set Font Size, Select background color [...]

Already in issue #36, font size need a bit of experimentations but it should be possible

> The windows for selecting background and font color change to the selected color after choosing one. 

Okay, that shouldn't happen, apparently I never noticed it because my installation use the system native dialog, only the one non-native QT dialog is affected, thanks for reporting :+1:
