### ISSUE TITLE
32bit AppImage

### ISSUE THREAD

**Issue by liamhallahan** [FrancescoCeruti/linux-show-player#84]
Heya, I've been trying to get Linux Show Player working using the .AppImage file. When I try opening it (after making it an executable), nothing happens except for a weird file being created in the same directory (i attach a screenshot of the file)

http://imgur.com/a/KC61Z

I'm Running Ubuntu 16.04 LTS, 32 Bit on a fairly old laptop (2.7 Gigs of memory, AMD Athlon II P320 Dual Core Processor).

What should I do?

**Comment by nethraam** [comment]
I've had the same problem. The problem is that you are running an i386 version of linux.
The app image runs only 64bit versions of linux. In most cases it is not a problem to install the amd64 version of ubuntu on an old computer. If you don't want to reinstall your linux, than you have to install "linux show player 0.4"

I hope this solution works for you.
Maarten

**Comment by liamhallahan** [comment]
That solved it; cheers! Running 0.4 and it's exactly what I need.

**Comment by FrancescoCeruti** [comment]
Hi @liamhallahan,
@nethraam is right, there is no 32bit AppImage, the current recipe doesn't allow to build a 32bit version, and right now I've no time to spend on it, anyway I'll reopen the issue to keep track of this problem.

If you really want to use the last version, on 32bit, you can always try to install it manually, it shouldn't be too hard.
